export interface Listing {
  id: string;
  title: string;
  price: number;
  address: string;
  neighborhood: string;
  beds: number;
  baths: number;
  sqft: number;
  score: number;
  photoUrl: string;
  isNew: boolean;
  hasGym: boolean;
  hasLaundry: boolean;
  hasParking: boolean;
  petFriendly: boolean;
  lat: number;
  lon: number;
  description: string;
  sourceUrl: string;
  commute: {
    oreoDrive: number;
    sugarCookieTransit: number;
    sugarCookieWalkMin: number;
    sugarCookieRoute: string;
    newtonDrive: number;
  };
  walkability: {
    coffee: { name: string; walkMin: number };
    grocery: { name: string; walkMin: number };
    park: { name: string; walkMin: number };
    restaurant: { name: string; walkMin: number };
    library: { name: string; walkMin: number };
    transitStop: { name: string; route: string; walkMin: number };
  };
  aiScores: {
    kitchenModernity: number;
    naturalLight: number;
    bathroomQuality: number;
    overallCondition: number;
    bedroomSize: number;
  };
  categoryScores: {
    unitQuality: number;
    commute: number;
    walkability: number;
    amenities: number;
    value: number;
  };
  hardFilterStatus: {
    passes: boolean;
    failures: string[];
  };
  reviews?: {
    rating: number;
    count: number;
    summary: string;
    source: string;
  };
  aiSummary: string;
  aiNotes: string[];
  details: {
    parking: string;
    laundry: string;
    ac: string;
    petPolicy: string;
    floor: string;
    leaseTerm: string;
    brokerFee: string;
  };
  photos: string[];
}

// ─── REAL LISTINGS — sourced March 21, 2026 ─────────────────────────────────

export const listings: Listing[] = [
  {
    id: "1",
    title: "New Construction 2BR/2BA — Underground Garage, In-Unit W/D",
    price: 3300,
    address: "50 Stedman St, Jamaica Plain, MA 02130",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 1067,
    score: 88,
    photoUrl:
      "https://images.craigslist.org/00K0K_6CwTXZjDtJt_0gw0gw_600x450.jpg",
    isNew: true,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3126,
    lon: -71.1115,
    sourceUrl:
      "https://boston.craigslist.org/gbs/apa/d/jamaica-plain-avail-1-new-jp-2bd-2ba-in/7918803568.html",
    description:
      "Brand new 21-unit elevator building near Forest Hills. In-unit W/D, central A/C, private balcony, open concept, engineered wood flooring, European cabinetry, quartz counters, stainless appliances, gas cooking, designer tile bathrooms, glass shower enclosures. Building has roof deck, recreation room, underground garage. One block from Forest Hills station.",
    commute: {
      oreoDrive: 14,
      sugarCookieTransit: 32,
      sugarCookieWalkMin: 14,
      sugarCookieRoute: "Route 39 (Forest Hills \u2192 Back Bay)",
      newtonDrive: 20,
    },
    walkability: {
      coffee: { name: "Caf\u00e9 Nero (Centre St)", walkMin: 8 },
      grocery: { name: "Stop & Shop (Centre St)", walkMin: 10 },
      park: { name: "Arnold Arboretum", walkMin: 5 },
      restaurant: { name: "Centre St restaurants", walkMin: 8 },
      library: { name: "JP Branch Library", walkMin: 10 },
      transitStop: {
        name: "Forest Hills Station",
        route: "Orange Line / Rte 39",
        walkMin: 3,
      },
    },
    aiScores: {
      kitchenModernity: 9,
      naturalLight: 8,
      bathroomQuality: 9,
      overallCondition: 10,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 90,
      commute: 62,
      walkability: 65,
      amenities: 92,
      value: 95,
    },
    hardFilterStatus: {
      passes: true,
      failures: [],
    },
    aiSummary:
      "Best value in the search \u2014 brand new construction at $3,300 for 2BR/2BA with in-unit W/D, central AC, underground garage, and pet-friendly. European cabinetry and quartz counters. Sugar Cookie\u2019s commute is 32 min via Route 39 (within 40 min max but on the longer side). Near Forest Hills, not Centre St proper, so walkability to coffee/restaurants is 8\u201310 min.",
    aiNotes: [
      "Incredible value \u2014 $700\u2013900/mo less than comparable new builds",
      "Brand new construction = no deferred maintenance issues",
      "Sugar Cookie commute is 32 min \u2014 within max but on the longer side",
      "Not on Centre St \u2014 need to walk 8\u201310 min for restaurants/coffee",
      "Forest Hills is a transit hub but the area itself is less charming",
      "Cats & small dogs welcome \u2014 pet requirement met",
      "No broker fee",
      "Recreation room and roof deck are nice common spaces",
      "+$50 water/sewer +$160 parking = ~$3,510 effective monthly cost",
      "Available July 1",
    ],
    details: {
      parking: "Underground garage ($160/mo)",
      laundry: "In-unit W/D (full-size, separate)",
      ac: "Central AC",
      petPolicy: "Cats & small dogs OK",
      floor: "Available on multiple floors",
      leaseTerm: "12 months",
      brokerFee: "None",
    },
    photos: [
      "https://images.craigslist.org/00K0K_6CwTXZjDtJt_0gw0gw_600x450.jpg",
      "https://images.craigslist.org/00r0r_bVLIiMFSqfP_0gw0gw_600x450.jpg",
      "https://images.craigslist.org/00U0U_3XlKhKcOCy1_0gw0gw_600x450.jpg",
      "https://images.craigslist.org/00e0e_7U5fxj1kmqQ_0gw0gw_600x450.jpg",
    ],
  },
  {
    id: "2",
    title: "MetroMark \u2014 2BR/2BA, Gym, Dog Park, 1 Month Free",
    price: 3177,
    address: "3593 Washington St, Jamaica Plain, MA 02130",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 933,
    score: 85,
    photoUrl: "https://picsum.photos/800/533?random=501",
    isNew: true,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3085,
    lon: -71.114,
    sourceUrl: "https://www.metromarkapts.com/",
    description:
      "MetroMark is a managed apartment community near Forest Hills. 2BR/2BA starting at $3,177. In-unit W/D, fitness center with yoga studio, on-site dog park, concierge, parking available. Currently offering 1 month FREE rent on select units. Near Forest Hills station and Route 39 bus.",
    commute: {
      oreoDrive: 16,
      sugarCookieTransit: 35,
      sugarCookieWalkMin: 14,
      sugarCookieRoute: "Near Forest Hills, Rte 39 \u2192 Back Bay",
      newtonDrive: 20,
    },
    walkability: {
      coffee: { name: "Local cafes", walkMin: 6 },
      grocery: { name: "Stop & Shop", walkMin: 8 },
      park: { name: "Southwest Corridor Park", walkMin: 3 },
      restaurant: { name: "Washington St restaurants", walkMin: 6 },
      library: { name: "JP Branch Library", walkMin: 10 },
      transitStop: {
        name: "Forest Hills / Rte 39",
        route: "Orange Line / Rte 39",
        walkMin: 5,
      },
    },
    aiScores: {
      kitchenModernity: 8,
      naturalLight: 7,
      bathroomQuality: 7,
      overallCondition: 8,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 75,
      commute: 58,
      walkability: 72,
      amenities: 88,
      value: 98,
    },
    hardFilterStatus: {
      passes: true,
      failures: [],
    },
    reviews: {
      rating: 3.5,
      count: 324,
      summary:
        "Brand new, clean, responsive staff. But thin floors = noise, smoking not enforced, aggressive rent increases at renewal.",
      source: "ApartmentRatings",
    },
    aiSummary:
      "Incredible value at $3,177 + 1 month free \u2014 lowest price for a fully amenitized 2BR/2BA in the search. Gym, in-unit W/D, dog park on-site, concierge. But reviews flag thin walls/floors causing noise, smoking policy not enforced, and aggressive rent increases at renewal. Sugar Cookie\u2019s commute is 35 min (within max). Parking confirmed but price TBD.",
    aiNotes: [
      "Lowest price in the search for a full-amenity 2BR/2BA",
      "1 month FREE rent currently offered \u2014 net effective ~$2,912/mo",
      "Dog park on-site \u2014 excellent for pet-friendly requirement",
      "Gym with yoga studio",
      "Reviews: 3.5/5 from 324 reviews \u2014 volume gives confidence",
      "Thin walls/floors are the #1 complaint",
      "Smoking enforcement is poor \u2014 smoke in hallways",
      "Aggressive rent increases reported at lease renewal",
      "Sugar Cookie commute is 35 min \u2014 workable but not ideal",
      "Parking available \u2014 confirm price when touring",
    ],
    details: {
      parking: "Available (price TBD)",
      laundry: "In-unit W/D",
      ac: "Central AC",
      petPolicy: "Very pet-friendly, on-site dog park",
      floor: "Multiple units available",
      leaseTerm: "12 months (1 month free promo)",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=501",
      "https://picsum.photos/800/533?random=502",
      "https://picsum.photos/800/533?random=503",
      "https://picsum.photos/800/533?random=504",
    ],
  },
  {
    id: "3",
    title: "Bell Olmsted Park \u2014 2BR/2BA with Gym, Pool & Garage",
    price: 4155,
    address: "161 S Huntington Ave, Boston, MA 02130",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 1006,
    score: 80,
    photoUrl: "https://picsum.photos/800/533?random=601",
    isNew: true,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3268,
    lon: -71.1097,
    sourceUrl: "https://www.bellolmstedpark.com/floor-plans/",
    description:
      "B2E floor plan at Bell Olmsted Park. 2BR/2BA, 1,006 sq ft. Modern finishes, in-unit washer/dryer, 24-hour fitness center, resort-style pool, controlled-access garage, pet spa, landscaped courtyard. Near MBTA Route 39 bus and Green Line E.",
    commute: {
      oreoDrive: 10,
      sugarCookieTransit: 25,
      sugarCookieWalkMin: 12,
      sugarCookieRoute: "Route 39 \u2192 Back Bay (walk to 216 Mass Ave)",
      newtonDrive: 20,
    },
    walkability: {
      coffee: { name: "Tbaar (nearest cafe)", walkMin: 13 },
      grocery: { name: "JP Convenience Store", walkMin: 7 },
      park: { name: "Olmsted Park", walkMin: 2 },
      restaurant: { name: "Top Mix Bar & Kitchen", walkMin: 8 },
      library: { name: "Brookline Main Library", walkMin: 15 },
      transitStop: {
        name: "S Huntington @ VA Hospital (Rte 39)",
        route: "Route 39",
        walkMin: 2,
      },
    },
    aiScores: {
      kitchenModernity: 8,
      naturalLight: 8,
      bathroomQuality: 7,
      overallCondition: 8,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 78,
      commute: 85,
      walkability: 45,
      amenities: 98,
      value: 68,
    },
    hardFilterStatus: {
      passes: true,
      failures: [],
    },
    reviews: {
      rating: 4.3,
      count: 282,
      summary:
        "Best community in Boston, great staff. But noise from above, thin walls, temperature control issues.",
      source: "ApartmentRatings",
    },
    aiSummary:
      "Highest amenity score in the search \u2014 24hr gym, pool, garage, in-unit W/D, pet spa. Great Route 39 access gives Sugar Cookie a 25 min commute. But walkability is genuinely weak: nearest real coffee shop is 13 min, grocery is a convenience store. At $4,155 it\u2019s in budget but not a bargain. Best for someone who values building amenities over neighborhood walkability.",
    aiNotes: [
      "Nearest cafe (Tbaar) is 13 min walk \u2014 no close coffee",
      "Grocery is a convenience store, not a full supermarket",
      "S Huntington corridor lacks the village feel of Centre St or Washington Sq",
      "Pool is a rare amenity in Boston rental market",
      "24-hr fitness center is excellent",
      "Olmsted Park is literally adjacent \u2014 beautiful green space",
      "Managed by Bell Partners \u2014 professional management",
      "Reviews: 4.3/5 (282 reviews) \u2014 well-reviewed overall",
      "Noise from above and thin walls are the main complaints",
    ],
    details: {
      parking: "Garage (controlled access, included)",
      laundry: "In-unit W/D (all units)",
      ac: "Central AC",
      petPolicy: "Pets allowed (restrictions apply); pet spa",
      floor: "Multiple units available",
      leaseTerm: "12+ months",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=601",
      "https://picsum.photos/800/533?random=602",
      "https://picsum.photos/800/533?random=603",
      "https://picsum.photos/800/533?random=604",
    ],
  },
  {
    id: "4",
    title: "Velo Forest Hills \u2014 2BR/2BA, Pool, Cinema Room, Dog Park",
    price: 3605,
    address: "3686 Washington St, Jamaica Plain, MA 02130",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 950,
    score: 78,
    photoUrl: "https://picsum.photos/800/533?random=701",
    isNew: true,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3005,
    lon: -71.1135,
    sourceUrl: "https://www.veloforesthills.com/",
    description:
      "Velo Forest Hills offers resort-style living near Forest Hills station. 2BR/2BA, ~950 sq ft. In-unit W/D, fitness center with yoga studio, swimming pool, cinema room, dog park, parking available. Steps from Forest Hills Orange Line and bus hub.",
    commute: {
      oreoDrive: 18,
      sugarCookieTransit: 38,
      sugarCookieWalkMin: 15,
      sugarCookieRoute: "Near Forest Hills, Rte 39 / Orange Line",
      newtonDrive: 18,
    },
    walkability: {
      coffee: { name: "Local cafes (Washington St)", walkMin: 5 },
      grocery: { name: "Stop & Shop", walkMin: 8 },
      park: { name: "Southwest Corridor Park", walkMin: 3 },
      restaurant: { name: "Washington St restaurants", walkMin: 5 },
      library: { name: "JP Branch Library", walkMin: 10 },
      transitStop: {
        name: "Forest Hills Station",
        route: "Orange Line / Rte 39",
        walkMin: 2,
      },
    },
    aiScores: {
      kitchenModernity: 8,
      naturalLight: 8,
      bathroomQuality: 7,
      overallCondition: 8,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 78,
      commute: 52,
      walkability: 72,
      amenities: 95,
      value: 82,
    },
    hardFilterStatus: {
      passes: true,
      failures: ["Borderline: Sugar Cookie transit 38 min (close to 40 min max)"],
    },
    reviews: {
      rating: 3.2,
      count: 107,
      summary:
        "New construction, friendly residents. But thin walls, street noise, poor sound insulation, weed smoke in halls.",
      source: "ApartmentRatings",
    },
    aiSummary:
      "Resort amenities (pool, cinema room, gym, dog park) at a reasonable $3,605. But thin walls and noise issues are a recurring complaint. Sugar Cookie\u2019s commute is borderline at 38 min \u2014 close to the 40 min max. Near Forest Hills station for good transit access. Dog park is a plus for pet owners.",
    aiNotes: [
      "Resort-style amenities: pool, cinema room, gym, yoga, dog park",
      "Sugar Cookie commute is 38 min \u2014 borderline (40 min max)",
      "Thin walls are the #1 complaint across reviews",
      "Weed smoke in hallways reported by multiple reviewers",
      "Street noise is noticeable",
      "New construction with modern finishes",
      "Dog park on-site \u2014 excellent for pets",
      "Near Forest Hills \u2014 good transit hub access",
      "Cinema room is a unique amenity",
    ],
    details: {
      parking: "Available (price TBD)",
      laundry: "In-unit W/D",
      ac: "Central AC",
      petPolicy: "Very pet-friendly, on-site dog park",
      floor: "Multiple units available",
      leaseTerm: "12 months",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=701",
      "https://picsum.photos/800/533?random=702",
      "https://picsum.photos/800/533?random=703",
      "https://picsum.photos/800/533?random=704",
    ],
  },
  {
    id: "5",
    title: "211 Green Street \u2014 Boutique New Construction, Rooftop Terrace",
    price: 3300,
    address: "211 Green St, Jamaica Plain, MA 02130",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 1077,
    score: 77,
    photoUrl: "https://picsum.photos/800/533?random=801",
    isNew: true,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3112,
    lon: -71.1073,
    sourceUrl: "https://www.live211green.com/",
    description:
      "Boutique 45-unit new construction near Green Street Orange Line station. 2BR/2BA, 1,077 sq ft. Floor-to-ceiling windows, in-unit W/D, fitness center, garage parking, rooftop terrace, elevator building. Walking distance to Centre St shops and restaurants.",
    commute: {
      oreoDrive: 13,
      sugarCookieTransit: 30,
      sugarCookieWalkMin: 12,
      sugarCookieRoute: "Green St \u2192 Orange Line (may need transfer)",
      newtonDrive: 22,
    },
    walkability: {
      coffee: { name: "Caf\u00e9 Nero (Centre St)", walkMin: 5 },
      grocery: { name: "Whole Foods (Centre St)", walkMin: 7 },
      park: { name: "Southwest Corridor Park", walkMin: 5 },
      restaurant: { name: "Centre St restaurants", walkMin: 5 },
      library: { name: "JP Branch Library", walkMin: 8 },
      transitStop: {
        name: "Green St Station (Orange Line)",
        route: "Orange Line",
        walkMin: 2,
      },
    },
    aiScores: {
      kitchenModernity: 8,
      naturalLight: 9,
      bathroomQuality: 8,
      overallCondition: 9,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 85,
      commute: 65,
      walkability: 78,
      amenities: 82,
      value: 85,
    },
    hardFilterStatus: {
      passes: true,
      failures: [
        "Maybe: Orange Line transit may require a transfer for Sugar Cookie",
      ],
    },
    aiSummary:
      "New boutique luxury at an excellent price \u2014 $3,300 for 1,077 sq ft with floor-to-ceiling windows, rooftop terrace, in-unit W/D, gym, and garage. Good walkability near Centre St (5\u20137 min). But Sugar Cookie\u2019s transit may require a transfer (Orange Line \u2192 Green Line or walk) to reach 216 Mass Ave. Too new for reviews.",
    aiNotes: [
      "Floor-to-ceiling windows \u2014 excellent natural light",
      "Boutique 45-unit building \u2014 less institutional feel",
      "Rooftop terrace with views",
      "Great price for new construction: $3,300",
      "Good walkability to Centre St shops (5\u20137 min)",
      "Green St Orange Line is 2 min walk",
      "Transit may require a transfer for Sugar Cookie \u2014 Orange to Green/walk",
      "No reviews yet \u2014 too new",
      "1,077 sq ft is spacious for the price",
    ],
    details: {
      parking: "Garage parking available",
      laundry: "In-unit W/D",
      ac: "Central AC",
      petPolicy: "Pets allowed",
      floor: "Multiple units available",
      leaseTerm: "12 months",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=801",
      "https://picsum.photos/800/533?random=802",
      "https://picsum.photos/800/533?random=803",
      "https://picsum.photos/800/533?random=804",
    ],
  },
  {
    id: "6",
    title: "2BR/2BA Condo \u2014 In-Unit W/D, Central AC, Parking & Patio",
    price: 3800,
    address: "Peter Parley Rd, Jamaica Plain, MA 02130",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 1093,
    score: 76,
    photoUrl:
      "https://images.craigslist.org/00P0P_aMwyFFicIiq_0x20oM_600x450.jpg",
    isNew: false,
    hasGym: false,
    hasLaundry: true,
    hasParking: true,
    petFriendly: false,
    lat: 42.312,
    lon: -71.112,
    sourceUrl:
      "https://boston.craigslist.org/gbs/apa/d/jamaica-plain-lovely-2br-2ba-parking/7921640202.html",
    description:
      "Lovely 2BR/2BA condo on Peter Parley Rd. 2nd floor, 1,093 sq ft. In-unit W/D, central A/C, HVAC gas heat, stainless appliances, granite countertops with island, walk-in shower, custom walk-in closet, patio, hardwood floors. 1 dedicated off-street parking spot. Near Centre St shops and Green Street T.",
    commute: {
      oreoDrive: 15,
      sugarCookieTransit: 30,
      sugarCookieWalkMin: 13,
      sugarCookieRoute: "Route 39 \u2192 Back Bay",
      newtonDrive: 22,
    },
    walkability: {
      coffee: { name: "JP Licks / Caf\u00e9 Nero", walkMin: 7 },
      grocery: { name: "Whole Foods (Centre St)", walkMin: 8 },
      park: { name: "Jamaica Pond", walkMin: 12 },
      restaurant: { name: "Centre St restaurants", walkMin: 7 },
      library: { name: "JP Branch Library", walkMin: 8 },
      transitStop: {
        name: "Green St Station (Orange Line)",
        route: "Orange Line",
        walkMin: 5,
      },
    },
    aiScores: {
      kitchenModernity: 7,
      naturalLight: 7,
      bathroomQuality: 7,
      overallCondition: 8,
      bedroomSize: 8,
    },
    categoryScores: {
      unitQuality: 75,
      commute: 70,
      walkability: 78,
      amenities: 60,
      value: 80,
    },
    hardFilterStatus: {
      passes: false,
      failures: ["No pets allowed \u2014 cannot get a cat"],
    },
    aiSummary:
      "Great unit at a good price \u2014 granite island kitchen, walk-in shower, large bedrooms, in-unit W/D, patio. Good walkability to Centre St shops (7\u20138 min). But no pets is a hard fail, and no gym (individual condo). Condo rental means individual landlord \u2014 potentially flexible on terms but less professional management.",
    aiNotes: [
      "FAILS: No pets allowed",
      "No gym \u2014 individual condo, not a managed building",
      "Granite + island kitchen is nice but not as modern as quartz/European cabinets",
      "Walk-in shower and custom closet are excellent touches",
      "Centre St walkability is solid at 7\u20138 min",
      "Orange Line at Green St is 5 min walk but requires transfer for Sugar Cookie",
      "Route 39 access is further \u2014 about 8\u201310 min walk",
      "Patio is a nice bonus",
      "1,093 sq ft is spacious",
    ],
    details: {
      parking: "Off-street (1 dedicated spot, included)",
      laundry: "In-unit W/D (full-size)",
      ac: "Central AC (HVAC)",
      petPolicy: "No pets",
      floor: "2nd floor",
      leaseTerm: "12 months",
      brokerFee: "1 month ($3,800)",
    },
    photos: [
      "https://images.craigslist.org/00P0P_aMwyFFicIiq_0x20oM_600x450.jpg",
      "https://images.craigslist.org/00S0S_cgdQ2JutgTY_0ip0dP_600x450.jpg",
      "https://images.craigslist.org/01212_j0Ue1bQgeIM_0CI0t2_600x450.jpg",
    ],
  },
  {
    id: "7",
    title: "1443 Beacon \u2014 2BR/2BA Coolidge Corner, Heat Included, Pool",
    price: 3925,
    address: "1443 Beacon St, Brookline, MA 02446",
    neighborhood: "Brookline",
    beds: 2,
    baths: 2,
    sqft: 1000,
    score: 74,
    photoUrl: "https://picsum.photos/800/533?random=901",
    isNew: false,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.344,
    lon: -71.1315,
    sourceUrl: "https://www.apartments.com/1443-beacon-brookline-ma/5c5j0gq/",
    description:
      "2BR/2BA at 1443 Beacon in the heart of Coolidge Corner. ~1,000 sq ft. In-unit W/D, gym, pool, parking available, pet-friendly. Heat included. Currently waiving last month\u2019s rent and security deposit. Steps from Green Line C and D, surrounded by shops, restaurants, and Coolidge Corner Theater.",
    commute: {
      oreoDrive: 10,
      sugarCookieTransit: 20,
      sugarCookieWalkMin: 10,
      sugarCookieRoute: "C Line \u2192 Hynes Convention Center",
      newtonDrive: 15,
    },
    walkability: {
      coffee: { name: "Tatte / Peet\u2019s (Coolidge Corner)", walkMin: 3 },
      grocery: { name: "Trader Joe\u2019s / Star Market", walkMin: 5 },
      park: { name: "Amory Park", walkMin: 5 },
      restaurant: { name: "Coolidge Corner restaurants", walkMin: 3 },
      library: { name: "Coolidge Corner Branch Library", walkMin: 5 },
      transitStop: {
        name: "Coolidge Corner (C Line)",
        route: "Green Line C",
        walkMin: 2,
      },
    },
    aiScores: {
      kitchenModernity: 6,
      naturalLight: 7,
      bathroomQuality: 6,
      overallCondition: 6,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 62,
      commute: 88,
      walkability: 92,
      amenities: 85,
      value: 65,
    },
    hardFilterStatus: {
      passes: true,
      failures: [],
    },
    reviews: {
      rating: 3.7,
      count: 21,
      summary:
        "Amazing Coolidge Corner location, but constant construction noise, overpriced, small gym.",
      source: "Google Reviews",
    },
    aiSummary:
      "Best walkability score in the search \u2014 Coolidge Corner is a vibrant neighborhood with everything within 3\u20135 min walk. Sugar Cookie\u2019s commute is excellent at 20 min via C Line. Heat included helps offset the $3,925 price. But reviews flag construction noise, dated finishes for the price, and a small gym. No last month or security deposit currently waived.",
    aiNotes: [
      "Best walkability: Coolidge Corner has coffee, grocery, restaurants within 3\u20135 min",
      "Sugar Cookie commute is excellent \u2014 20 min via C Line",
      "Heat included saves ~$100\u2013150/mo",
      "No last month rent, no security deposit currently",
      "Reviews flag constant construction noise",
      "Finishes are dated for the $3,925 price point",
      "Gym is small per reviews",
      "Pool is a rare amenity",
      "Pet-friendly building",
      "Coolidge Corner has the neighborhood village feel Sugar Cookie wants",
    ],
    details: {
      parking: "Available (price TBD)",
      laundry: "In-unit W/D",
      ac: "Central AC",
      petPolicy: "Pet-friendly",
      floor: "Multiple units available",
      leaseTerm: "12 months",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=901",
      "https://picsum.photos/800/533?random=902",
      "https://picsum.photos/800/533?random=903",
      "https://picsum.photos/800/533?random=904",
    ],
  },
  {
    id: "8",
    title: "Kent St Brookline Village \u2014 2BR/1BA, Heat & Water Included",
    price: 3450,
    address: "Kent St, Brookline Village, MA 02447",
    neighborhood: "Brookline",
    beds: 2,
    baths: 1,
    sqft: 1000,
    score: 72,
    photoUrl: "https://picsum.photos/800/533?random=1001",
    isNew: false,
    hasGym: false,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3325,
    lon: -71.1168,
    sourceUrl:
      "https://boston.craigslist.org/gbs/apa/d/brookline-village-very-spacious-open/7921048980.html",
    description:
      "Spacious 2BR/1BA in Brookline Village. ~1,000 sq ft. In-unit W/D, dishwasher, AC, hardwood floors. Heat and water included. Off-street parking available ($200/mo). Cats and dogs welcome ($50/mo pet fee). Near D Line Brookline Village station.",
    commute: {
      oreoDrive: 8,
      sugarCookieTransit: 20,
      sugarCookieWalkMin: 9,
      sugarCookieRoute: "D Line (Brookline Village \u2192 Hynes/Copley)",
      newtonDrive: 16,
    },
    walkability: {
      coffee: { name: "Brookline Village cafes", walkMin: 4 },
      grocery: { name: "Trader Joe\u2019s (Brookline)", walkMin: 6 },
      park: { name: "Larz Anderson Park", walkMin: 5 },
      restaurant: { name: "Brookline Village restaurants", walkMin: 4 },
      library: { name: "Brookline Main Library", walkMin: 10 },
      transitStop: {
        name: "Brookline Village (D Line)",
        route: "Green Line D",
        walkMin: 2,
      },
    },
    aiScores: {
      kitchenModernity: 6,
      naturalLight: 7,
      bathroomQuality: 5,
      overallCondition: 7,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 62,
      commute: 90,
      walkability: 78,
      amenities: 50,
      value: 85,
    },
    hardFilterStatus: {
      passes: false,
      failures: ["Only 1 bathroom (need 2)"],
    },
    aiSummary:
      "Great value with heat and water included, excellent commute for both (8 min drive for Oreo, 20 min transit for Sugar Cookie). But only 1 bath is a hard fail. No gym. Pet-friendly with cats and dogs ($50/mo fee). Parking available at $200/mo. Hardwood floors and spacious layout.",
    aiNotes: [
      "FAILS: Only 1 bathroom",
      "No gym \u2014 no building amenities",
      "Heat + water included saves ~$150\u2013200/mo",
      "Excellent commute: 8 min drive (Oreo), 20 min transit (Sugar Cookie)",
      "D Line at Brookline Village is 2 min walk",
      "Cats and dogs OK ($50/mo pet fee)",
      "Parking available at $200/mo extra",
      "Hardwood floors throughout",
      "Spacious at 1,000 sq ft",
      "Effective rent with utilities included is very competitive",
    ],
    details: {
      parking: "Off-street ($200/mo)",
      laundry: "In-unit W/D, dishwasher",
      ac: "AC (window/split)",
      petPolicy: "Cats and dogs ($50/mo pet fee)",
      floor: "Not specified",
      leaseTerm: "12 months",
      brokerFee: "Not specified",
    },
    photos: [
      "https://picsum.photos/800/533?random=1001",
      "https://picsum.photos/800/533?random=1002",
      "https://picsum.photos/800/533?random=1003",
    ],
  },
  {
    id: "9",
    title: "The Brookliner \u2014 2BR/2BA Luxury, Peloton Gym, EV Charging",
    price: 5150,
    address: "5 Washington St, Brookline, MA 02445",
    neighborhood: "Brookline",
    beds: 2,
    baths: 2,
    sqft: 1027,
    score: 55,
    photoUrl: "https://picsum.photos/800/533?random=1101",
    isNew: false,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3393,
    lon: -71.1361,
    sourceUrl: "https://thebrookliner.com/floorplans/",
    description:
      "B6 floor plan at The Brookliner, 1,027 sq ft. 2BR/2BA. Calacatta Quartz countertops, GE smart appliances, LVT flooring. Peloton fitness center, rooftop terrace with fire pits, pet spa, covered garage with EV charging. Green Line C at Washington Square. Currently offering up to 2 months free on 14-month lease.",
    commute: {
      oreoDrive: 12,
      sugarCookieTransit: 18,
      sugarCookieWalkMin: 8,
      sugarCookieRoute: "Green Line C \u2192 Hynes (4 min walk to office)",
      newtonDrive: 15,
    },
    walkability: {
      coffee: { name: "Starbucks (Washington Square)", walkMin: 1 },
      grocery: { name: "7-Eleven (nearest)", walkMin: 1 },
      park: { name: "Beaconsfield Terraces", walkMin: 4 },
      restaurant: { name: "Bartaco / Washington Sq Tavern", walkMin: 1 },
      library: { name: "Brookline Main Library", walkMin: 8 },
      transitStop: {
        name: "Washington Square (C Line)",
        route: "Green Line C",
        walkMin: 1,
      },
    },
    aiScores: {
      kitchenModernity: 10,
      naturalLight: 9,
      bathroomQuality: 9,
      overallCondition: 10,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 95,
      commute: 90,
      walkability: 88,
      amenities: 98,
      value: 20,
    },
    hardFilterStatus: {
      passes: false,
      failures: [
        "Over budget: $5,150/mo base (max $4,500)",
        "Parking is $200/mo extra \u2192 effective $5,350/mo",
      ],
    },
    reviews: {
      rating: 4.7,
      count: 32,
      summary:
        "Best-reviewed building. Modern, great staff, secure. Minor: trash chute bugs, game room closes 10pm.",
      source: "Google Reviews",
    },
    aiSummary:
      "Dream apartment \u2014 best unit quality, best walkability in Brookline, best commute, best amenities, best reviews (4.7/5). Washington Square location with everything within 1 min walk. But at $5,150/mo + $200 parking = $5,350 effective, it\u2019s way over budget. With 2 months free on 14-month lease, net effective is ~$4,386/mo \u2014 still over ideal. Worth negotiating.",
    aiNotes: [
      "FAILS: Over budget at $5,150 + $200 parking",
      "With 2 months free on 14-mo lease: ~$4,386/mo net effective",
      "Best unit finishes in the search \u2014 Calacatta Quartz, smart appliances",
      "Best walkability \u2014 everything within 1\u20134 min",
      "Best commute for Sugar Cookie \u2014 18 min total, 8 min walking",
      "Best reviews: 4.7/5 (32 reviews)",
      "Peloton gym is excellent",
      "Pet spa for future cat",
      "EV charging if they ever go electric",
      "Could negotiate: offer 24-month lease for lower rent?",
    ],
    details: {
      parking: "Covered garage ($200/mo, EV charging available)",
      laundry: "In-unit W/D",
      ac: "Central AC (Nest thermostat)",
      petPolicy: "Pet-friendly; pet spa",
      floor: "4th floor (Unit 422)",
      leaseTerm: "14 months (promo: up to 2 months free)",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=1101",
      "https://picsum.photos/800/533?random=1102",
      "https://picsum.photos/800/533?random=1103",
      "https://picsum.photos/800/533?random=1104",
    ],
  },
  {
    id: "10",
    title: "Hancock Village / Franklin \u2014 2BR/2BA, 25K sqft Community Center",
    price: 4195,
    address: "1 Hancock Village Dr, Brookline, MA 02467",
    neighborhood: "Brookline",
    beds: 2,
    baths: 2,
    sqft: 1000,
    score: 68,
    photoUrl: "https://picsum.photos/800/533?random=1201",
    isNew: true,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3215,
    lon: -71.152,
    sourceUrl: "https://www.liveathancockvillage.com/",
    description:
      "New construction at Hancock Village / Franklin. 2BR/2BA, ~1,000 sq ft. In-unit W/D, 25,000 sq ft community center with gym and pool, parking included. Currently offering 1 month free rent + $10K Jordan\u2019s Furniture credit. Pet-friendly community.",
    commute: {
      oreoDrive: 15,
      sugarCookieTransit: 40,
      sugarCookieWalkMin: 14,
      sugarCookieRoute: "Bus \u2192 Green Line (likely requires transfer)",
      newtonDrive: 12,
    },
    walkability: {
      coffee: { name: "Local cafes", walkMin: 8 },
      grocery: { name: "Star Market", walkMin: 10 },
      park: { name: "D. Blakely Hoar Sanctuary", walkMin: 3 },
      restaurant: { name: "Hancock Village dining", walkMin: 8 },
      library: { name: "Putterham Branch Library", walkMin: 12 },
      transitStop: {
        name: "Bus stop (Rte 51/65)",
        route: "MBTA Bus 51/65",
        walkMin: 10,
      },
    },
    aiScores: {
      kitchenModernity: 7,
      naturalLight: 7,
      bathroomQuality: 7,
      overallCondition: 8,
      bedroomSize: 8,
    },
    categoryScores: {
      unitQuality: 72,
      commute: 55,
      walkability: 50,
      amenities: 90,
      value: 70,
    },
    hardFilterStatus: {
      passes: false,
      failures: [
        "Borderline: Sugar Cookie transit 40 min (at absolute max, likely requires transfer)",
      ],
    },
    reviews: {
      rating: 3.0,
      count: 45,
      summary:
        "Hancock Village (old): 3.0/5 with mice/mold complaints. Franklin (new construction) reviews are positive but limited.",
      source: "ApartmentRatings / Google",
    },
    aiSummary:
      "Great amenities with a 25,000 sq ft community center (gym + pool) and generous promos (1 month free + $10K Jordan\u2019s Furniture). But far from transit \u2014 Sugar Cookie\u2019s commute is 40 min with likely transfers, at the absolute max. Old Hancock Village had mice/mold issues; the Franklin (new) portion is better but managed by the same company. Close to Newton (12 min drive).",
    aiNotes: [
      "BORDERLINE: Sugar Cookie transit 40 min \u2014 at absolute max, likely requires transfer",
      "25,000 sq ft community center is massive",
      "Pool access \u2014 rare in Boston",
      "Promo: 1 month free + $10K Jordan\u2019s Furniture credit",
      "Old Hancock Village has mice/mold complaints",
      "Franklin is new construction \u2014 different quality",
      "Same management company for old and new \u2014 some concern",
      "Far from transit \u2014 10 min walk to bus stop",
      "Closest to Newton at 12 min drive",
      "Pet-friendly community",
    ],
    details: {
      parking: "Included",
      laundry: "In-unit W/D",
      ac: "Central AC",
      petPolicy: "Pet-friendly",
      floor: "Multiple units available",
      leaseTerm: "12 months (1 month free promo)",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=1201",
      "https://picsum.photos/800/533?random=1202",
      "https://picsum.photos/800/533?random=1203",
      "https://picsum.photos/800/533?random=1204",
    ],
  },
  {
    id: "11",
    title: "Coolidge Corner Luxury 1+Den \u2014 Gym, Pets, C/D Line",
    price: 4400,
    address: "Harvard St, Coolidge Corner, Brookline, MA 02446",
    neighborhood: "Brookline",
    beds: 2,
    baths: 1,
    sqft: 825,
    score: 65,
    photoUrl: "https://picsum.photos/800/533?random=1301",
    isNew: false,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.342,
    lon: -71.1312,
    sourceUrl:
      "https://boston.craigslist.org/gbs/apa/d/brookline-lux-den-in-unit-d-c-gym-pets/7916461445.html",
    description:
      "Luxury 1BR+den (used as 2BR) in Coolidge Corner. 825 sq ft. In-unit W/D, gym, central AC, elevator building. Garage parking available ($300/mo). Cats ($50/mo), dogs ($75/mo). Steps from C and D Green Line stops. Surrounded by Coolidge Corner shops and restaurants.",
    commute: {
      oreoDrive: 10,
      sugarCookieTransit: 20,
      sugarCookieWalkMin: 10,
      sugarCookieRoute: "C/D Line \u2192 Hynes Convention Center",
      newtonDrive: 15,
    },
    walkability: {
      coffee: { name: "Tatte / Peet\u2019s (Coolidge Corner)", walkMin: 2 },
      grocery: { name: "Trader Joe\u2019s", walkMin: 4 },
      park: { name: "Amory Park", walkMin: 5 },
      restaurant: { name: "Coolidge Corner restaurants", walkMin: 2 },
      library: { name: "Coolidge Corner Branch Library", walkMin: 5 },
      transitStop: {
        name: "Coolidge Corner (C/D Line)",
        route: "Green Line C/D",
        walkMin: 3,
      },
    },
    aiScores: {
      kitchenModernity: 9,
      naturalLight: 7,
      bathroomQuality: 8,
      overallCondition: 9,
      bedroomSize: 5,
    },
    categoryScores: {
      unitQuality: 78,
      commute: 88,
      walkability: 92,
      amenities: 80,
      value: 35,
    },
    hardFilterStatus: {
      passes: false,
      failures: [
        "Only 1 bathroom (need 2)",
        "Effective cost $4,700/mo with $300 parking",
        "825 sq ft \u2014 small for 2BR",
        "Broker fee: $4,400",
      ],
    },
    aiSummary:
      "Luxury finishes in the best walkable location (Coolidge Corner). But 1 bath is a hard fail, only 825 sq ft is small for 2BR, and effectively $4,700/mo with parking + $4,400 broker fee. The den may not be a true second bedroom. Great commute and walkability don\u2019t overcome the hard filter failures.",
    aiNotes: [
      "FAILS: Only 1 bathroom",
      "FAILS: Effective $4,700/mo with $300 parking",
      "FAILS: 825 sq ft is small \u2014 den may not fit queen bed",
      "FAILS: $4,400 broker fee",
      "Luxury finishes \u2014 kitchen scores 9/10",
      "Best walkable neighborhood in the search",
      "Excellent commute: 20 min for Sugar Cookie, 10 min drive for Oreo",
      "Cats $50/mo, dogs $75/mo",
      "1+den marketed as 2BR \u2014 verify den size",
    ],
    details: {
      parking: "Garage ($300/mo)",
      laundry: "In-unit W/D",
      ac: "Central AC",
      petPolicy: "Cats ($50/mo), dogs ($75/mo)",
      floor: "Elevator building",
      leaseTerm: "12 months",
      brokerFee: "1 month ($4,400)",
    },
    photos: [
      "https://picsum.photos/800/533?random=1301",
      "https://picsum.photos/800/533?random=1302",
      "https://picsum.photos/800/533?random=1303",
    ],
  },
  {
    id: "12",
    title: "West Roxbury New Construction \u2014 2BR/2BA, 1 Month Free",
    price: 3900,
    address: "Gardner St, West Roxbury, MA 02132",
    neighborhood: "Roslindale",
    beds: 2,
    baths: 2,
    sqft: 1000,
    score: 62,
    photoUrl: "https://picsum.photos/800/533?random=1401",
    isNew: true,
    hasGym: false,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.296,
    lon: -71.145,
    sourceUrl:
      "https://boston.craigslist.org/gbs/apa/d/west-roxbury-bath-no-fee-available-now/7919409754.html",
    description:
      "New construction 2BR/2BA in West Roxbury. ~1,000 sq ft. In-unit W/D, central AC, off-street parking included, pet-friendly. 1 month free rent, no broker fee. Available now. Bus connections to Forest Hills and downtown.",
    commute: {
      oreoDrive: 22,
      sugarCookieTransit: 45,
      sugarCookieWalkMin: 15,
      sugarCookieRoute: "Bus connections (likely requires transfer)",
      newtonDrive: 15,
    },
    walkability: {
      coffee: { name: "Local cafes (Centre St WR)", walkMin: 8 },
      grocery: { name: "Roche Bros", walkMin: 10 },
      park: { name: "Billings Field", walkMin: 5 },
      restaurant: { name: "West Roxbury restaurants", walkMin: 8 },
      library: { name: "West Roxbury Branch Library", walkMin: 10 },
      transitStop: {
        name: "Bus stop (Rte 36/37)",
        route: "MBTA Bus 36/37",
        walkMin: 8,
      },
    },
    aiScores: {
      kitchenModernity: 7,
      naturalLight: 7,
      bathroomQuality: 7,
      overallCondition: 9,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 75,
      commute: 35,
      walkability: 55,
      amenities: 70,
      value: 85,
    },
    hardFilterStatus: {
      passes: false,
      failures: [
        "Sugar Cookie commute 45+ min with transfers (max 40)",
        "No gym",
      ],
    },
    aiSummary:
      "Good value new construction with 1 month free and no broker fee. In-unit W/D, central AC, parking, pets OK. But too far from Sugar Cookie\u2019s work \u2014 45+ min transit with bus transfers is a hard fail. No gym either. The 22 min drive for Oreo is also the longest in the search. Close to Newton (15 min) is a plus.",
    aiNotes: [
      "FAILS: Sugar Cookie commute 45+ min with transfers",
      "FAILS: No gym",
      "1 month free rent \u2014 net effective ~$3,575/mo",
      "No broker fee",
      "New construction \u2014 good condition",
      "In-unit W/D, central AC, parking all included",
      "Pet-friendly",
      "West Roxbury is quiet and suburban",
      "Far from transit \u2014 8 min walk to nearest bus stop",
      "Close to Newton (15 min drive)",
      "Oreo drive is longest in search at 22 min",
    ],
    details: {
      parking: "Off-street (included)",
      laundry: "In-unit W/D",
      ac: "Central AC",
      petPolicy: "Pets OK",
      floor: "Not specified",
      leaseTerm: "12 months (1 month free)",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=1401",
      "https://picsum.photos/800/533?random=1402",
      "https://picsum.photos/800/533?random=1403",
    ],
  },
  {
    id: "13",
    title: "The Tremont — In-Unit W/D, Gym, Garage, Roof Deck",
    price: 5065,
    address: "1480 Tremont St, Boston, MA 02120",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 950,
    score: 50,
    photoUrl: "https://picsum.photos/800/533?random=1501",
    isNew: true,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3310,
    lon: -71.0975,
    sourceUrl: "https://thetremontboston.com/",
    description:
      "Contemporary 2BR/2BA at The Tremont, a 66-unit new construction on Tremont St. 24-hour fitness center, roof deck with grills and skyline views, courtyard garden, dog run. In-unit W/D, wood floors, stone countertops, stainless appliances. Assigned garage parking. Steps from Route 39 bus and short walk to Brigham Circle (E Line).",
    commute: {
      oreoDrive: 8,
      sugarCookieTransit: 22,
      sugarCookieWalkMin: 10,
      sugarCookieRoute: "Route 39 \u2192 Back Bay (or walk to E Line Brigham Circle)",
      newtonDrive: 22,
    },
    walkability: {
      coffee: { name: "Area cafes (Brigham Circle)", walkMin: 7 },
      grocery: { name: "Star Market (Huntington)", walkMin: 10 },
      park: { name: "Southwest Corridor Park", walkMin: 5 },
      restaurant: { name: "Tremont St restaurants", walkMin: 3 },
      library: { name: "Parker Hill Branch", walkMin: 10 },
      transitStop: { name: "Tremont St @ Brigham (Rte 39)", route: "Route 39 / E Line", walkMin: 5 },
    },
    aiScores: {
      kitchenModernity: 8,
      naturalLight: 8,
      bathroomQuality: 8,
      overallCondition: 9,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 82,
      commute: 85,
      walkability: 55,
      amenities: 95,
      value: 25,
    },
    hardFilterStatus: {
      passes: false,
      failures: [
        "Over budget: actual 2BR pricing is $5,065-$5,826/mo (heat/HW included)",
      ],
    },
    aiSummary:
      "Over budget: actual 2BR pricing is $5,065-$5,826/mo (heat/HW included). Checks every box: in-unit W/D, gym, garage parking, pet-friendly, 2BR/2BA, new construction — but at $5,065-$5,826/mo significantly over budget. The roof deck with skyline views is a great bonus. Walkability to coffee/grocery is moderate (7-10 min) but the transit access is strong. Short drive for Oreo (8 min). Not viable at this price point.",
    aiNotes: [
      "OVER BUDGET: Actual 2BR pricing is $5,065-$5,826/mo (heat/HW included)",
      "New construction, 66 units — well-managed",
      "Roof deck with grills + skyline views",
      "Dog run on-site — great for future pet",
      "Route 39 stops right outside on Tremont St",
      "Brigham Circle E Line is ~5 min walk",
      "Walkability to grocery is 10 min — you'd probably drive",
      "Mission Hill adjacent — Sugar Cookie's colleague warned about living too close to students, but Tremont St is south of main campus area",
    ],
    details: {
      parking: "Assigned garage parking (included or low cost)",
      laundry: "In-unit W/D",
      ac: "Central AC",
      petPolicy: "Pet-friendly (dog run on-site)",
      floor: "Multiple floors available",
      leaseTerm: "12 months",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=1501",
      "https://picsum.photos/800/533?random=1502",
      "https://picsum.photos/800/533?random=1503",
      "https://picsum.photos/800/533?random=1504",
    ],
  },
  {
    id: "14",
    title: "The Laneway — New Build, Gym, In-Unit W/D, Central AC",
    price: 3150,
    address: "9 Burney St, Roxbury Crossing, MA 02120",
    neighborhood: "JP",
    beds: 2,
    baths: 1.5,
    sqft: 900,
    score: 79,
    photoUrl: "https://picsum.photos/800/533?random=1601",
    isNew: true,
    hasGym: true,
    hasLaundry: true,
    hasParking: false,
    petFriendly: true,
    lat: 42.3310,
    lon: -71.0940,
    sourceUrl: "https://www.apartments.com/the-laneway-roxbury-crossing-ma/cqn66ff/",
    description:
      "Brand new 24-unit construction at The Laneway. 2BR/1.5BA with central A/C, in-unit W/D, gym, conference room, lounge, shared kitchen, bike storage, roof deck with summer kitchen and skyline views. Water, hot water, sewer included. No undergrad students policy. Near Route 39 and Roxbury Crossing Orange Line.",
    commute: {
      oreoDrive: 8,
      sugarCookieTransit: 22,
      sugarCookieWalkMin: 10,
      sugarCookieRoute: "Route 39 \u2192 Back Bay (or walk to E Line Brigham Circle)",
      newtonDrive: 24,
    },
    walkability: {
      coffee: { name: "Cafe options (Tremont St)", walkMin: 8 },
      grocery: { name: "Star Market", walkMin: 12 },
      park: { name: "Southwest Corridor Park", walkMin: 4 },
      restaurant: { name: "Tremont St dining", walkMin: 5 },
      library: { name: "Parker Hill Branch", walkMin: 8 },
      transitStop: { name: "Roxbury Crossing (Orange Line)", route: "Orange Line / Rte 39", walkMin: 5 },
    },
    aiScores: {
      kitchenModernity: 8,
      naturalLight: 7,
      bathroomQuality: 7,
      overallCondition: 9,
      bedroomSize: 6,
    },
    categoryScores: {
      unitQuality: 78,
      commute: 82,
      walkability: 48,
      amenities: 78,
      value: 95,
    },
    hardFilterStatus: {
      passes: false,
      failures: ["Parking not confirmed \u2014 need to call and verify"],
    },
    aiSummary:
      "Incredible price for new construction with in-unit W/D, gym, and central AC at only $3,150. The roof deck with summer kitchen is a standout amenity. No-undergrad policy means a quieter building. Main uncertainty is parking \u2014 need to call to confirm. Walkability to grocery is weak (12 min). Water/hot water/sewer included boosts the value further.",
    aiNotes: [
      "NEEDS VERIFICATION: Parking availability \u2014 call to confirm",
      "Cheapest new construction with gym + in-unit W/D in the search",
      "No-undergrad policy = quieter building",
      "Roof deck with summer kitchen \u2014 great for hosting",
      "Utilities partially included (water, hot water, sewer)",
      "Grocery is 12 min walk \u2014 you'd drive",
      "24 units = boutique feel",
      "Near Roxbury Crossing, not the most charming area but improving rapidly",
    ],
    details: {
      parking: "Not confirmed \u2014 call to verify",
      laundry: "In-unit W/D",
      ac: "Central AC",
      petPolicy: "Pet-friendly",
      floor: "Multiple floors available",
      leaseTerm: "12 months",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=1601",
      "https://picsum.photos/800/533?random=1602",
      "https://picsum.photos/800/533?random=1603",
    ],
  },
  {
    id: "15",
    title: "225 Centre — Garage, Gym, Pet-Friendly, 2 Months Free",
    price: 3400,
    address: "225 Centre St, Boston, MA 02119",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 1075,
    score: 81,
    photoUrl: "https://picsum.photos/800/533?random=1701",
    isNew: true,
    hasGym: true,
    hasLaundry: false,
    hasParking: true,
    petFriendly: true,
    lat: 42.3230,
    lon: -71.0990,
    sourceUrl: "https://www.apartments.com/225-centre-boston-ma/gj8nlvw/",
    description:
      "Modern LEED Silver building at Jackson Square. 2BR/2BA, 1,075 sq ft. Fitness center, garage parking, bike storage. Pet-friendly. Near MBTA Orange Line (Jackson Square) and Southwest Corridor bike path. Currently offering 2 months free rent. On-site laundry (not confirmed in-unit \u2014 call to verify).",
    commute: {
      oreoDrive: 12,
      sugarCookieTransit: 28,
      sugarCookieWalkMin: 12,
      sugarCookieRoute: "Route 39 \u2192 Back Bay",
      newtonDrive: 22,
    },
    walkability: {
      coffee: { name: "Centre St cafes", walkMin: 5 },
      grocery: { name: "Tropical Foods / Hi-Lo", walkMin: 5 },
      park: { name: "Southwest Corridor Park", walkMin: 2 },
      restaurant: { name: "Centre St / Jackson Sq dining", walkMin: 4 },
      library: { name: "JP Branch Library", walkMin: 12 },
      transitStop: { name: "Jackson Square (Orange Line)", route: "Orange Line / Rte 39", walkMin: 3 },
    },
    aiScores: {
      kitchenModernity: 7,
      naturalLight: 8,
      bathroomQuality: 7,
      overallCondition: 8,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 75,
      commute: 72,
      walkability: 80,
      amenities: 75,
      value: 92,
    },
    hardFilterStatus: {
      passes: false,
      failures: ["In-unit laundry not confirmed \u2014 may be on-site shared only"],
    },
    aiSummary:
      "Strong value play at $3,400 with 2 months free (net effective ~$2,833/mo). Gym, garage, pet-friendly, LEED Silver. Good walkability to coffee and groceries on Centre St. Main uncertainty: in-unit laundry status \u2014 need to verify. Jackson Square area is up-and-coming, more diverse and affordable than deeper JP. Route 39 access is solid.",
    aiNotes: [
      "NEEDS VERIFICATION: In-unit laundry \u2014 call to confirm",
      "2 months free rent promo \u2014 net effective ~$2,833/mo",
      "LEED Silver certification = energy efficient, lower utility bills",
      "Southwest Corridor Park is adjacent \u2014 great running/biking path",
      "Jackson Square is more affordable but less charming than Centre St proper",
      "Route 39 bus stop very close",
      "Garage parking is a big plus",
    ],
    details: {
      parking: "Garage (included)",
      laundry: "On-site (verify in-unit availability)",
      ac: "Central AC (LEED Silver building)",
      petPolicy: "Pet-friendly",
      floor: "Multiple floors available",
      leaseTerm: "12 months",
      brokerFee: "None (2 months free promo)",
    },
    photos: [
      "https://picsum.photos/800/533?random=1701",
      "https://picsum.photos/800/533?random=1702",
      "https://picsum.photos/800/533?random=1703",
      "https://picsum.photos/800/533?random=1704",
    ],
  },
  {
    id: "16",
    title: "The Longwood — Balconies, Gym, Pet-Friendly, Near E Line",
    price: 4200,
    address: "1575 Tremont St, Boston, MA 02120",
    neighborhood: "JP",
    beds: 2,
    baths: 1.5,
    sqft: 950,
    score: 70,
    photoUrl: "https://picsum.photos/800/533?random=1801",
    isNew: false,
    hasGym: true,
    hasLaundry: false,
    hasParking: true,
    petFriendly: true,
    lat: 42.3335,
    lon: -71.0975,
    sourceUrl: "https://thelongwoodapartments.com/",
    description:
      "2BR/1.5BA at The Longwood, 1575 Tremont St. Private balcony in every unit. Fitness center, concierge, shared entertainment spaces, outdoor dog area. Reserved parking. Stainless appliances, gas cooking, individually controlled heat and A/C. On-site laundry (not in-unit). Near Brigham Circle (E Line) and Route 39 bus.",
    commute: {
      oreoDrive: 7,
      sugarCookieTransit: 20,
      sugarCookieWalkMin: 10,
      sugarCookieRoute: "E Line (Brigham Circle) \u2192 Symphony",
      newtonDrive: 22,
    },
    walkability: {
      coffee: { name: "Brigham Circle cafes", walkMin: 7 },
      grocery: { name: "Star Market (Huntington)", walkMin: 10 },
      park: { name: "Evans Way Park", walkMin: 5 },
      restaurant: { name: "Tremont/Huntington dining", walkMin: 5 },
      library: { name: "Parker Hill Branch", walkMin: 8 },
      transitStop: { name: "Brigham Circle (E Line)", route: "Green Line E / Rte 39", walkMin: 7 },
    },
    aiScores: {
      kitchenModernity: 5,
      naturalLight: 7,
      bathroomQuality: 5,
      overallCondition: 6,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 58,
      commute: 90,
      walkability: 55,
      amenities: 70,
      value: 55,
    },
    hardFilterStatus: {
      passes: false,
      failures: ["No in-unit laundry (on-site shared only)"],
    },
    aiSummary:
      "2BR starts at $4,200 confirmed. Best commute balance in the search \u2014 7 min drive for Oreo, 20 min transit for Sugar Cookie via E Line. Gym, parking, pet-friendly, private balcony. But no in-unit laundry is a hard fail. The building is older and finishes are dated compared to new construction. Decent price for the location. Concierge is a nice touch.",
    aiNotes: [
      "FAILS: No in-unit laundry (on-site shared only)",
      "Best commute combo: 7 min drive + 20 min transit",
      "Every unit has a private balcony \u2014 rare in Boston",
      "Concierge service",
      "Building is older \u2014 finishes not as modern as new builds",
      "Outdoor dog area for future cat/pet needs",
      "Brigham Circle E Line is 7 min walk",
      "Price range goes as low as $2,455 for smaller 2BRs \u2014 ask about options",
    ],
    details: {
      parking: "Reserved parking (included)",
      laundry: "On-site (shared)",
      ac: "Individually controlled AC",
      petPolicy: "Pet-friendly (restrictions may apply)",
      floor: "Multiple floors, private balconies",
      leaseTerm: "12 months",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=1801",
      "https://picsum.photos/800/533?random=1802",
      "https://picsum.photos/800/533?random=1803",
    ],
  },
  {
    id: "17",
    title: "3193 Washington — Chef\u2019s Kitchen, In-Unit W/D, Central AC",
    price: 3400,
    address: "3193 Washington St, Jamaica Plain, MA 02130",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 870,
    score: 75,
    photoUrl: "https://picsum.photos/800/533?random=1901",
    isNew: true,
    hasGym: false,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3140,
    lon: -71.1100,
    sourceUrl: "https://www.apartments.com/3193-washington-st-jamaica-plain-ma/t586c18/",
    description:
      "Boutique 32-unit luxury building near Stony Brook Orange Line. 2BR/2BA, 870 sq ft. Chef\u2019s kitchen with huge island, gas cooking, stainless appliances, high ceilings, recessed lighting. In-unit laundry, central air. Parking available nearby. Near Route 39 bus.",
    commute: {
      oreoDrive: 13,
      sugarCookieTransit: 30,
      sugarCookieWalkMin: 13,
      sugarCookieRoute: "Route 39 \u2192 Back Bay",
      newtonDrive: 22,
    },
    walkability: {
      coffee: { name: "Ula Caf\u00e9 / Centre St cafes", walkMin: 6 },
      grocery: { name: "Whole Foods (Centre St)", walkMin: 8 },
      park: { name: "Stony Brook Reservation", walkMin: 5 },
      restaurant: { name: "Washington St / Centre St dining", walkMin: 5 },
      library: { name: "JP Branch Library", walkMin: 8 },
      transitStop: { name: "Stony Brook (Orange Line)", route: "Orange Line / Rte 39", walkMin: 4 },
    },
    aiScores: {
      kitchenModernity: 9,
      naturalLight: 8,
      bathroomQuality: 7,
      overallCondition: 9,
      bedroomSize: 6,
    },
    categoryScores: {
      unitQuality: 82,
      commute: 65,
      walkability: 72,
      amenities: 65,
      value: 88,
    },
    hardFilterStatus: {
      passes: false,
      failures: ["No gym in building"],
    },
    aiSummary:
      "The chef\u2019s kitchen with gas cooking and huge island is exactly the modern kitchen Oreo wants. In-unit W/D, central AC, pet-friendly, parking \u2014 hits most requirements. But no gym. At $3,400 for a brand-new 2BR/2BA with these finishes, it\u2019s exceptional value. Boutique 32-unit building means quieter than big complexes. Good walkability to Centre St shops.",
    aiNotes: [
      "FAILS: No gym (32-unit boutique building)",
      "Chef\u2019s kitchen with island is the best kitchen layout in the search",
      "Gas cooking \u2014 a real perk for anyone who cooks",
      "High ceilings + recessed lighting = modern feel",
      "32 units = quieter, more personal building",
      "Stony Brook Orange Line is 4 min walk but requires transfer for Sugar Cookie",
      "Route 39 bus is accessible but further walk",
      "Could join a nearby gym (Healthworks, YMCA) to fill the gap",
    ],
    details: {
      parking: "Available nearby (verify cost)",
      laundry: "In-unit W/D",
      ac: "Central AC",
      petPolicy: "Pet-friendly (verify restrictions)",
      floor: "Multiple floors available",
      leaseTerm: "12 months",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=1901",
      "https://picsum.photos/800/533?random=1902",
      "https://picsum.photos/800/533?random=1903",
    ],
  },
  {
    id: "18",
    title: "Mosaic on the Riverway \u2014 In-Unit W/D, Gym, Garage, 2BR/2BA",
    price: 3395,
    address: "74-80 Fenwood Rd, Boston, MA 02115",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 1000,
    score: 65,
    photoUrl: "https://picsum.photos/800/533?random=2001",
    isNew: true,
    hasGym: true,
    hasLaundry: true,
    hasParking: true,
    petFriendly: true,
    lat: 42.3370,
    lon: -71.1040,
    sourceUrl: "https://www.apartments.com/mosaic-on-the-riverway-boston-ma/hrr3fs1/",
    description:
      "LEED Silver 11-floor, 145-unit building steps from Fenwood Rd E Line stop \u2014 directly in the Longwood Medical Area. 2BR/2BA with in-unit W/D, granite countertops, stainless steel appliances, oversize windows. Building has fitness center, club room, roof deck, bike storage, garage parking. Right on Huntington Ave at the E Line and Route 39.",
    commute: {
      oreoDrive: 5,
      sugarCookieTransit: 18,
      sugarCookieWalkMin: 8,
      sugarCookieRoute: "E Line (Fenwood Rd) \u2192 Symphony (walk to 216 Mass Ave)",
      newtonDrive: 22,
    },
    walkability: {
      coffee: { name: "Tatte / Pressed (Longwood)", walkMin: 5 },
      grocery: { name: "Star Market (Huntington)", walkMin: 8 },
      park: { name: "Emerald Necklace / Evans Way", walkMin: 3 },
      restaurant: { name: "Longwood dining options", walkMin: 5 },
      library: { name: "BPL (Copley) via E Line", walkMin: 20 },
      transitStop: { name: "Fenwood Rd (E Line)", route: "Green Line E / Route 39", walkMin: 2 },
    },
    aiScores: {
      kitchenModernity: 8,
      naturalLight: 9,
      bathroomQuality: 8,
      overallCondition: 9,
      bedroomSize: 7,
    },
    categoryScores: {
      unitQuality: 85,
      commute: 95,
      walkability: 62,
      amenities: 95,
      value: 90,
    },
    hardFilterStatus: {
      passes: false,
      failures: [
        "No confirmed 2BR availability \u2014 condo building with individual rentals, only 2 units total available",
      ],
    },
    aiSummary:
      "This is a condo building, not a managed apartment community \u2014 2BR availability is unconfirmed. Call to verify. If available: 5 min drive for Oreo to Longwood. 18 min transit for Sugar Cookie via E Line. In-unit W/D, gym, garage, 2BR/2BA, LEED Silver, pet-friendly \u2014 all at $3,395. Steps from Fenwood Rd E Line stop and Route 39 bus. The Longwood Medical Area location means Oreo could practically walk to work. Oversize windows = great natural light. The only weakness is walkability to everyday errands (grocery 8 min, no close indie coffee shops), but transit access is phenomenal.",
    aiNotes: [
      "WARNING: This is a condo building, not a managed apartment community. 2BR availability is unconfirmed.",
      "5 min drive to BIDMC \u2014 shortest in the entire search",
      "Could walk or bike to work in good weather",
      "Fenwood Rd E Line stop is 2 min walk",
      "Route 39 bus stops right on Huntington Ave outside",
      "LEED Silver = energy efficient, lower utility bills",
      "145 units = well-managed mid-rise",
      "Roof deck and club room for hosting guests",
      "Grocery is 8 min walk \u2014 you'd drive for big shops",
      "Longwood area has hospital cafeterias and some restaurants but limited nightlife/indie shops",
      "11 floors \u2014 upper floors will have great views",
    ],
    details: {
      parking: "Garage parking (available for purchase)",
      laundry: "In-unit W/D",
      ac: "Central AC (LEED Silver)",
      petPolicy: "Pet-friendly (verify restrictions)",
      floor: "11-floor building, multiple units available",
      leaseTerm: "12 months",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=2001",
      "https://picsum.photos/800/533?random=2002",
      "https://picsum.photos/800/533?random=2003",
      "https://picsum.photos/800/533?random=2004",
    ],
  },
  {
    id: "19",
    title: "J VUE at the LMA \u2014 Pool, Concierge, 1 Month Free",
    price: 3335,
    address: "75 Saint Alphonsus St, Boston, MA 02120",
    neighborhood: "JP",
    beds: 2,
    baths: 2,
    sqft: 961,
    score: 86,
    photoUrl: "https://picsum.photos/800/533?random=2101",
    isNew: true,
    hasGym: true,
    hasLaundry: false,
    hasParking: true,
    petFriendly: true,
    lat: 42.3345,
    lon: -71.1000,
    sourceUrl: "https://www.jvueapartments.com/",
    description:
      "2BR/2BA at J VUE (formerly CityView at Longwood), 961-1,150 sq ft. Parquet wood floors, large balconies, outdoor pool, 24-hour concierge, fitness center, parking available. Pet-friendly ($50 cats, $75 dogs). Currently offering 1 month free rent. One block from Green Line E stop, in the Longwood Medical Area.",
    commute: {
      oreoDrive: 5,
      sugarCookieTransit: 18,
      sugarCookieWalkMin: 8,
      sugarCookieRoute: "E Line (Brigham Circle) \u2192 Symphony",
      newtonDrive: 22,
    },
    walkability: {
      coffee: { name: "Hospital/campus cafes", walkMin: 5 },
      grocery: { name: "Star Market (Huntington)", walkMin: 8 },
      park: { name: "Evans Way Park", walkMin: 4 },
      restaurant: { name: "Brigham Circle dining", walkMin: 5 },
      library: { name: "Parker Hill Branch", walkMin: 8 },
      transitStop: { name: "Brigham Circle (E Line)", route: "Green Line E / Route 39", walkMin: 3 },
    },
    aiScores: {
      kitchenModernity: 6,
      naturalLight: 7,
      bathroomQuality: 6,
      overallCondition: 7,
      bedroomSize: 8,
    },
    categoryScores: {
      unitQuality: 68,
      commute: 95,
      walkability: 62,
      amenities: 88,
      value: 92,
    },
    hardFilterStatus: {
      passes: false,
      failures: ["On-site laundry only \u2014 not in-unit W/D"],
    },
    aiSummary:
      "Incredible location and value \u2014 $3,335 for a 2BR/2BA with pool, gym, concierge, and 1 month free (net effective ~$3,057/mo). One block from E Line. Oreo could walk to work. Large units (up to 1,150 sq ft) with balconies. But laundry is on-site shared, not in-unit \u2014 a hard fail. The finishes are older (parquet floors, not modern) but units are spacious. Worth touring to see if the space and location overcome the laundry issue.",
    aiNotes: [
      "FAILS: No in-unit laundry (on-site shared)",
      "1 month free rent promo \u2014 net effective ~$3,057/mo for 2BR/2BA",
      "POOL \u2014 rare amenity in Boston",
      "24-hour concierge",
      "Large balconies with views",
      "Oreo could walk or bike to BIDMC",
      "Units are older \u2014 parquet floors, not modern luxury finishes",
      "961-1,150 sq ft is very spacious for a 2BR",
      "Pet-friendly: cats $50/mo, dogs $75/mo",
      "Up to 1,150 sq ft \u2014 plenty of room for guests",
    ],
    details: {
      parking: "Available (verify cost)",
      laundry: "On-site (shared, not in-unit)",
      ac: "Central AC",
      petPolicy: "Cats $50/mo, Dogs $75/mo",
      floor: "Multiple floors, large balconies",
      leaseTerm: "12 months",
      brokerFee: "None (1 month free promo)",
    },
    photos: [
      "https://picsum.photos/800/533?random=2101",
      "https://picsum.photos/800/533?random=2102",
      "https://picsum.photos/800/533?random=2103",
    ],
  },
  {
    id: "20",
    title: "900 Huntington \u2014 In-Unit W/D, Right at Riverway E Stop",
    price: 2795,
    address: "900 Huntington Ave, Boston, MA 02115",
    neighborhood: "JP",
    beds: 2,
    baths: 1,
    sqft: 750,
    score: 45,
    photoUrl: "https://picsum.photos/800/533?random=2201",
    isNew: true,
    hasGym: true,
    hasLaundry: true,
    hasParking: false,
    petFriendly: true,
    lat: 42.3370,
    lon: -71.1070,
    sourceUrl: "https://www.apartments.com/900-huntington-ave-boston-ma/95czfs4/",
    description:
      "2BR at 900 Huntington Ave. In-unit W/D, fitness center, balcony, high-speed internet, stainless steel appliances, pet-friendly. Riverway Station (E Line) is literally 0.0 miles away \u2014 you walk out the door onto the platform. Budget-friendly at $2,795.",
    commute: {
      oreoDrive: 7,
      sugarCookieTransit: 18,
      sugarCookieWalkMin: 8,
      sugarCookieRoute: "E Line (Riverway) \u2192 Symphony",
      newtonDrive: 22,
    },
    walkability: {
      coffee: { name: "Hospital cafes", walkMin: 7 },
      grocery: { name: "Star Market (Huntington)", walkMin: 6 },
      park: { name: "Olmsted Park / Riverway", walkMin: 1 },
      restaurant: { name: "Huntington Ave options", walkMin: 5 },
      library: { name: "Parker Hill Branch", walkMin: 10 },
      transitStop: { name: "Riverway (E Line)", route: "Green Line E / Route 39", walkMin: 0 },
    },
    aiScores: {
      kitchenModernity: 6,
      naturalLight: 6,
      bathroomQuality: 5,
      overallCondition: 6,
      bedroomSize: 5,
    },
    categoryScores: {
      unitQuality: 57,
      commute: 92,
      walkability: 65,
      amenities: 72,
      value: 98,
    },
    hardFilterStatus: {
      passes: false,
      failures: [
        "Only 1 bathroom (need 1.5 minimum)",
        "750 sq ft \u2014 may be tight for 2BR (check bedroom sizes)",
        "Parking not confirmed",
        "2BR availability unconfirmed \u2014 building may only have 1BR units",
      ],
    },
    aiSummary:
      "2BR availability is unconfirmed \u2014 building may only have 1BR units. The cheapest listing in the entire search at $2,795, and it has in-unit W/D and a gym. Riverway E Line stop is literally at the front door \u2014 0.0 miles. But only 1 bath and 750 sq ft is tight for a 2BR. Parking unknown. The price is unbeatable and you'd save $600-1,500/mo vs other options. Worth touring to see if the space works despite being small.",
    aiNotes: [
      "FAILS: Only 1 bathroom",
      "FAILS: 750 sq ft may be too small",
      "NEEDS VERIFICATION: Parking availability",
      "Cheapest in the entire search \u2014 $2,795",
      "E Line stop is 0.0 miles \u2014 literally at the door",
      "In-unit W/D + gym at this price is extraordinary",
      "Riverway / Olmsted Park is 1 min walk",
      "Could save $600-1,500/mo vs other options for a nearby gym membership",
      "Stainless appliances and balcony",
    ],
    details: {
      parking: "Not confirmed \u2014 verify",
      laundry: "In-unit W/D",
      ac: "Verify type",
      petPolicy: "Pet-friendly",
      floor: "Balcony unit",
      leaseTerm: "12 months",
      brokerFee: "Verify",
    },
    photos: [
      "https://picsum.photos/800/533?random=2201",
      "https://picsum.photos/800/533?random=2202",
    ],
  },
  {
    id: "21",
    title: "Beautiful 2BR by Riverway T \u2014 Renovated, Exposed Brick, $3,145",
    price: 3145,
    address: "Mission Hill (near Riverway T), Boston, MA 02115",
    neighborhood: "JP",
    beds: 2,
    baths: 1,
    sqft: 900,
    score: 68,
    photoUrl: "https://picsum.photos/800/533?random=2301",
    isNew: true,
    hasGym: false,
    hasLaundry: false,
    hasParking: true,
    petFriendly: true,
    lat: 42.3427,
    lon: -71.0922,
    sourceUrl: "https://boston.craigslist.org/gbs/apa/d/boston-beautiful-2bed-apt-by-riverway-9/7920122464.html",
    description:
      "Newly renovated 2BR with exposed brick, hardwood floors, modern kitchen and bathroom. Off-street parking available. Laundry on-site. Cats allowed. Hot water included. 0.02 miles from Riverway E Line stop. Near Brigham and Women's Hospital. Available September 1, 2026. No broker fee.",
    commute: {
      oreoDrive: 6,
      sugarCookieTransit: 18,
      sugarCookieWalkMin: 8,
      sugarCookieRoute: "E Line (Riverway) \u2192 Symphony",
      newtonDrive: 22,
    },
    walkability: {
      coffee: { name: "Brigham Circle cafes", walkMin: 6 },
      grocery: { name: "Star Market", walkMin: 7 },
      park: { name: "Olmsted Park / Riverway", walkMin: 2 },
      restaurant: { name: "Huntington Ave dining", walkMin: 5 },
      library: { name: "Parker Hill Branch", walkMin: 8 },
      transitStop: { name: "Riverway (E Line)", route: "Green Line E / Route 39", walkMin: 1 },
    },
    aiScores: {
      kitchenModernity: 7,
      naturalLight: 7,
      bathroomQuality: 7,
      overallCondition: 7,
      bedroomSize: 6,
    },
    categoryScores: {
      unitQuality: 70,
      commute: 92,
      walkability: 68,
      amenities: 40,
      value: 82,
    },
    hardFilterStatus: {
      passes: false,
      failures: [
        "Only 1 bathroom (need 1.5 minimum)",
        "No in-unit laundry (on-site shared)",
        "No gym",
      ],
    },
    aiSummary:
      "Charming renovated unit with exposed brick and hardwood \u2014 has real character. Practically on top of the Riverway E Line stop (0.02 mi). Great commute for both. Parking available. But fails on 1 bath, no in-unit laundry, and no gym. At $3,145 with hot water included, it's good value for the location. The exposed brick gives it an Inner Sunset SF vibe that Sugar Cookie might love.",
    aiNotes: [
      "FAILS: Only 1 bath",
      "FAILS: No in-unit laundry",
      "FAILS: No gym",
      "Exposed brick + hardwood = great character",
      "0.02 mi from Riverway E Line \u2014 essentially on the platform",
      "Hot water included",
      "Cats allowed",
      "Near Brigham and Women's Hospital",
      "No broker fee",
      "Contact: Benjamin Apartments, 781-228-1766",
    ],
    details: {
      parking: "Off-street (available)",
      laundry: "On-site (shared)",
      ac: "Verify",
      petPolicy: "Cats allowed",
      floor: "Not specified",
      leaseTerm: "12 months",
      brokerFee: "None",
    },
    photos: [
      "https://picsum.photos/800/533?random=2301",
      "https://picsum.photos/800/533?random=2302",
    ],
  },
];

export const keyLocations = [
  {
    name: "Oreo\u2019s Work (Longwood)",
    lat: 42.3386,
    lon: -71.1044,
    type: "work" as const,
  },
  {
    name: "Sugar Cookie\u2019s Work (216 Mass Ave)",
    lat: 42.3454,
    lon: -71.0854,
    type: "work" as const,
  },
  {
    name: "Family (Newton)",
    lat: 42.337,
    lon: -71.2092,
    type: "family" as const,
  },
];
