/**
 * Seed script: inserts 8-10 realistic sample listings for development/demo.
 * Uses real JP and Brookline addresses with varied scores.
 */

import { createClient } from '@libsql/client';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const TURSO_URL = process.env.TURSO_URL;
const TURSO_AUTH_TOKEN = process.env.TURSO_AUTH_TOKEN;

function nowISO() {
  return new Date().toISOString().replace('T', ' ').slice(0, 19);
}

const SEED_LISTINGS = [
  // --- High scoring (85+) ---
  {
    listing: {
      id: 'seed-001',
      source: 'craigslist',
      source_url: 'https://boston.craigslist.org/gbs/apa/d/jamaica-plain-sunny-2br/seed001.html',
      source_id: 'seed001',
      title: 'Stunning Renovated 2BR/2BA - Jamaica Plain Centre St',
      price: 2800,
      bedrooms: 2,
      bathrooms: 2,
      sqft: 1050,
      address: '710 Centre St, Jamaica Plain, MA 02130',
      neighborhood: 'Jamaica Plain',
      lat: 42.3155,
      lon: -71.1120,
      description: 'Beautiful sun-drenched 2 bedroom, 2 bath in the heart of JP. Renovated kitchen with granite countertops, stainless steel appliances, and dishwasher. In-unit washer/dryer. Central AC. Hardwood floors throughout. Large bedrooms with ample closet space. Steps to Centre St shops and restaurants. Garage parking included. Pet friendly (cats and small dogs). No broker fee. Available Sept 1.',
      parking_type: 'garage',
      laundry_type: 'in-unit',
      ac_type: 'central',
      pet_policy: 'cats-and-dogs',
      has_gym: false,
      has_dishwasher: true,
      floor: 2,
      broker_fee_months: 0,
      lease_term_months: 12,
    },
    photos: [
      'https://picsum.photos/seed/apt1-kitchen/800/600',
      'https://picsum.photos/seed/apt1-living/800/600',
      'https://picsum.photos/seed/apt1-bed1/800/600',
      'https://picsum.photos/seed/apt1-bed2/800/600',
      'https://picsum.photos/seed/apt1-bath/800/600',
    ],
    scores: {
      composite_score: 88.5,
      passes_hard_filters: 1,
      fail_reasons: null,
      akhil_drive_min: 8,
      jayshree_transit_min: 22,
      jayshree_walk_min: 6,
      jayshree_transfers: 0,
      jayshree_transit_route: 'Route 39',
      newton_drive_min: 18,
      kitchen_modernity: 9,
      natural_light: 9,
      bathroom_quality: 8,
      overall_condition: 9,
      bedroom_size_score: 8,
      walk_coffee: 2.5,
      walk_park: 3.0,
      walk_grocery: 5.0,
      walk_restaurant: 2.0,
      walk_library: 8.0,
      walk_transit_stop: 4.5,
      nearest_transit_stop: 'Centre St @ Seaverns Ave',
      nearest_transit_route: 'Route 39',
      ai_summary: 'Exceptional renovated 2BR with modern kitchen, in-unit laundry, central AC, and garage parking on Centre St. No broker fee.',
      ai_notes: '{"red_flags":[],"highlights":["renovated kitchen","in-unit laundry","central AC","garage parking","no broker fee"]}',
      ai_confidence: 0.95,
    },
  },
  {
    listing: {
      id: 'seed-002',
      source: 'building',
      source_url: 'https://www.bellolmstedpark.com/floor-plans',
      source_id: 'bell-olmsted-2br-a',
      title: 'Bell Olmsted Park - 2BR/2BA Luxury',
      price: 3400,
      bedrooms: 2,
      bathrooms: 2,
      sqft: 1100,
      address: '655 Centre St, Jamaica Plain, MA 02130',
      neighborhood: 'Jamaica Plain',
      lat: 42.3135,
      lon: -71.1145,
      description: 'Luxury 2 bedroom apartment at Bell Olmsted Park. Modern open-concept kitchen with quartz countertops, stainless appliances, island. In-unit washer/dryer. Central HVAC. Fitness center, rooftop deck, package lockers. Garage parking available. Pet friendly with dog park.',
      parking_type: 'garage',
      laundry_type: 'in-unit',
      ac_type: 'central',
      pet_policy: 'cats-and-dogs',
      has_gym: true,
      has_dishwasher: true,
      floor: 4,
      broker_fee_months: 0,
      lease_term_months: 12,
    },
    photos: [
      'https://picsum.photos/seed/bell-kitchen/800/600',
      'https://picsum.photos/seed/bell-living/800/600',
      'https://picsum.photos/seed/bell-bed/800/600',
      'https://picsum.photos/seed/bell-bath/800/600',
      'https://picsum.photos/seed/bell-gym/800/600',
      'https://picsum.photos/seed/bell-rooftop/800/600',
    ],
    scores: {
      composite_score: 86.2,
      passes_hard_filters: 1,
      fail_reasons: null,
      akhil_drive_min: 9,
      jayshree_transit_min: 24,
      jayshree_walk_min: 7,
      jayshree_transfers: 0,
      jayshree_transit_route: 'Route 39',
      newton_drive_min: 17,
      kitchen_modernity: 9,
      natural_light: 8,
      bathroom_quality: 9,
      overall_condition: 9,
      bedroom_size_score: 7,
      walk_coffee: 3.0,
      walk_park: 1.0,
      walk_grocery: 6.0,
      walk_restaurant: 3.5,
      walk_library: 10.0,
      walk_transit_stop: 5.5,
      nearest_transit_stop: 'Centre St @ Burroughs St',
      nearest_transit_route: 'Route 39',
      ai_summary: 'Modern luxury building with gym, rooftop, in-unit laundry, and central AC. Higher price but excellent amenities. Adjacent to Olmsted Park.',
      ai_notes: '{"red_flags":[],"highlights":["luxury building","gym","rooftop","in-unit laundry","quartz countertops","dog park"]}',
      ai_confidence: 0.92,
    },
  },
  {
    listing: {
      id: 'seed-003',
      source: 'craigslist',
      source_url: 'https://boston.craigslist.org/gbs/apa/d/brookline-modern-2br/seed003.html',
      source_id: 'seed003',
      title: 'Modern 2BR/1.5BA Near Coolidge Corner',
      price: 3100,
      bedrooms: 2,
      bathrooms: 1.5,
      sqft: 950,
      address: '45 Harvard St, Brookline, MA 02446',
      neighborhood: 'Brookline',
      lat: 42.3415,
      lon: -71.1290,
      description: 'Charming 2 bed 1.5 bath near Coolidge Corner. Updated kitchen with dishwasher. In-building laundry. Mini-split AC. Hardwood floors. Walk to Green Line C. Cats allowed. One off-street parking spot included. Available August 1. No broker fee.',
      parking_type: 'driveway',
      laundry_type: 'in-building',
      ac_type: 'mini-split',
      pet_policy: 'cats-only',
      has_gym: false,
      has_dishwasher: true,
      floor: 1,
      broker_fee_months: 0,
      lease_term_months: 12,
    },
    photos: [
      'https://picsum.photos/seed/brook-kitchen/800/600',
      'https://picsum.photos/seed/brook-living/800/600',
      'https://picsum.photos/seed/brook-bed/800/600',
      'https://picsum.photos/seed/brook-bath/800/600',
    ],
    scores: {
      composite_score: 85.1,
      passes_hard_filters: 1,
      fail_reasons: null,
      akhil_drive_min: 12,
      jayshree_transit_min: 18,
      jayshree_walk_min: 4,
      jayshree_transfers: 0,
      jayshree_transit_route: 'Green Line C',
      newton_drive_min: 15,
      kitchen_modernity: 7,
      natural_light: 8,
      bathroom_quality: 7,
      overall_condition: 8,
      bedroom_size_score: 7,
      walk_coffee: 2.0,
      walk_park: 4.0,
      walk_grocery: 3.0,
      walk_restaurant: 1.5,
      walk_library: 5.0,
      walk_transit_stop: 3.0,
      nearest_transit_stop: 'Coolidge Corner',
      nearest_transit_route: 'Green Line C',
      ai_summary: 'Well-located 2BR near Coolidge Corner with mini-split AC, updated kitchen, and no broker fee. Great walkability.',
      ai_notes: '{"red_flags":[],"highlights":["Coolidge Corner location","no broker fee","mini-split AC","walk to Green Line"]}',
      ai_confidence: 0.90,
    },
  },

  // --- Medium scoring (60-75) ---
  {
    listing: {
      id: 'seed-004',
      source: 'craigslist',
      source_url: 'https://boston.craigslist.org/gbs/apa/d/jamaica-plain-spacious-2br/seed004.html',
      source_id: 'seed004',
      title: 'Spacious 2BR/1BA - JP Pondside',
      price: 2700,
      bedrooms: 2,
      bathrooms: 1.5,
      sqft: 900,
      address: '30 Pond St, Jamaica Plain, MA 02130',
      neighborhood: 'Jamaica Plain',
      lat: 42.3175,
      lon: -71.1160,
      description: 'Spacious 2 bedroom near Jamaica Pond. Recently painted. In-building coin laundry. No AC. Street parking. No pets. 1 month broker fee. Available October 1. Close to bus routes.',
      parking_type: 'street',
      laundry_type: 'in-building',
      ac_type: 'none',
      pet_policy: 'no-pets',
      has_gym: false,
      has_dishwasher: false,
      floor: 3,
      broker_fee_months: 1.0,
      lease_term_months: 12,
    },
    photos: [
      'https://picsum.photos/seed/pond-kitchen/800/600',
      'https://picsum.photos/seed/pond-living/800/600',
      'https://picsum.photos/seed/pond-bed/800/600',
    ],
    scores: {
      composite_score: 62.3,
      passes_hard_filters: 1,
      fail_reasons: null,
      akhil_drive_min: 10,
      jayshree_transit_min: 28,
      jayshree_walk_min: 8,
      jayshree_transfers: 0,
      jayshree_transit_route: 'Route 39',
      newton_drive_min: 20,
      kitchen_modernity: 5,
      natural_light: 6,
      bathroom_quality: 5,
      overall_condition: 6,
      bedroom_size_score: 7,
      walk_coffee: 5.0,
      walk_park: 2.0,
      walk_grocery: 8.0,
      walk_restaurant: 5.0,
      walk_library: 12.0,
      walk_transit_stop: 7.0,
      nearest_transit_stop: 'Centre St @ Seaverns Ave',
      nearest_transit_route: 'Route 39',
      ai_summary: 'Affordable 2BR near Jamaica Pond but no AC, no dishwasher, no pets, and has broker fee. Older finishes.',
      ai_notes: '{"red_flags":["no AC","broker fee","no pets allowed","no dishwasher"],"highlights":["near Jamaica Pond","spacious","affordable"]}',
      ai_confidence: 0.88,
    },
  },
  {
    listing: {
      id: 'seed-005',
      source: 'building',
      source_url: 'https://www.thebrookliner.com/floor-plans',
      source_id: 'brookliner-2br',
      title: 'The Brookliner - 2BR/2BA',
      price: 4200,
      bedrooms: 2,
      bathrooms: 2,
      sqft: 1150,
      address: '111 Centre St, Brookline, MA 02446',
      neighborhood: 'Brookline',
      lat: 42.3348,
      lon: -71.1215,
      description: 'Brand new luxury 2 bedroom at The Brookliner. High-end finishes, quartz counters, smart home features. In-unit washer/dryer. Central AC. Fitness center, coworking space, pet spa. Garage parking $200/mo extra. Pets welcome.',
      parking_type: 'garage',
      laundry_type: 'in-unit',
      ac_type: 'central',
      pet_policy: 'cats-and-dogs',
      has_gym: true,
      has_dishwasher: true,
      floor: 6,
      broker_fee_months: 0,
      lease_term_months: 12,
    },
    photos: [
      'https://picsum.photos/seed/brookliner-kitchen/800/600',
      'https://picsum.photos/seed/brookliner-living/800/600',
      'https://picsum.photos/seed/brookliner-bed/800/600',
      'https://picsum.photos/seed/brookliner-bath/800/600',
      'https://picsum.photos/seed/brookliner-gym/800/600',
    ],
    scores: {
      composite_score: 72.4,
      passes_hard_filters: 1,
      fail_reasons: null,
      akhil_drive_min: 11,
      jayshree_transit_min: 20,
      jayshree_walk_min: 5,
      jayshree_transfers: 0,
      jayshree_transit_route: 'Green Line D',
      newton_drive_min: 16,
      kitchen_modernity: 10,
      natural_light: 8,
      bathroom_quality: 10,
      overall_condition: 10,
      bedroom_size_score: 7,
      walk_coffee: 3.5,
      walk_park: 4.0,
      walk_grocery: 5.0,
      walk_restaurant: 3.0,
      walk_library: 7.0,
      walk_transit_stop: 4.0,
      nearest_transit_stop: 'Brookline Village',
      nearest_transit_route: 'Green Line D',
      ai_summary: 'Top-tier luxury building with perfect finishes but premium pricing at $4200 brings the composite score down. All amenities included.',
      ai_notes: '{"red_flags":["high price","parking extra $200/mo"],"highlights":["brand new","smart home","pet spa","coworking","top finishes"]}',
      ai_confidence: 0.95,
    },
  },
  {
    listing: {
      id: 'seed-006',
      source: 'craigslist',
      source_url: 'https://boston.craigslist.org/gbs/apa/d/roslindale-2br-near-sq/seed006.html',
      source_id: 'seed006',
      title: '2BR/1.5BA Roslindale near Square',
      price: 2600,
      bedrooms: 2,
      bathrooms: 1.5,
      sqft: 875,
      address: '15 Birch St, Roslindale, MA 02131',
      neighborhood: 'Roslindale',
      lat: 42.2865,
      lon: -71.1250,
      description: 'Nice 2 bedroom in Roslindale near the village. Updated kitchen. In-building laundry. Window AC units provided. Off-street parking. Cats OK. No broker fee. Available Sept 1.',
      parking_type: 'driveway',
      laundry_type: 'in-building',
      ac_type: 'window',
      pet_policy: 'cats-only',
      has_gym: false,
      has_dishwasher: true,
      floor: 2,
      broker_fee_months: 0,
      lease_term_months: 12,
    },
    photos: [
      'https://picsum.photos/seed/roz-kitchen/800/600',
      'https://picsum.photos/seed/roz-living/800/600',
      'https://picsum.photos/seed/roz-bed/800/600',
    ],
    scores: {
      composite_score: 68.7,
      passes_hard_filters: 1,
      fail_reasons: null,
      akhil_drive_min: 15,
      jayshree_transit_min: 35,
      jayshree_walk_min: 12,
      jayshree_transfers: 1,
      jayshree_transit_route: 'Bus 34 + Orange Line',
      newton_drive_min: 22,
      kitchen_modernity: 7,
      natural_light: 7,
      bathroom_quality: 6,
      overall_condition: 7,
      bedroom_size_score: 7,
      walk_coffee: 5.0,
      walk_park: 3.0,
      walk_grocery: 4.0,
      walk_restaurant: 4.5,
      walk_library: 6.0,
      walk_transit_stop: 10.0,
      nearest_transit_stop: 'Centre St @ Seaverns Ave',
      nearest_transit_route: 'Route 39',
      ai_summary: 'Affordable 2BR in Roslindale with updated kitchen and no broker fee. Farther from transit but good price.',
      ai_notes: '{"red_flags":["window AC","farther from transit"],"highlights":["affordable","updated kitchen","no broker fee","near Roslindale Village"]}',
      ai_confidence: 0.87,
    },
  },
  {
    listing: {
      id: 'seed-007',
      source: 'craigslist',
      source_url: 'https://boston.craigslist.org/gbs/apa/d/south-huntington-2br/seed007.html',
      source_id: 'seed007',
      title: '2BR/2BA S Huntington - Walk to E Line',
      price: 3300,
      bedrooms: 2,
      bathrooms: 2,
      sqft: 1000,
      address: '95 S Huntington Ave, Jamaica Plain, MA 02130',
      neighborhood: 'South Huntington',
      lat: 42.3270,
      lon: -71.1060,
      description: 'Bright 2 bed 2 bath on South Huntington. Renovated kitchen and baths. In-unit laundry. Mini-split AC in every room. Building gym. Covered parking available. Cats and dogs welcome. Near Heath St Green Line stop. No broker fee. 12 month lease. Available August.',
      parking_type: 'garage',
      laundry_type: 'in-unit',
      ac_type: 'mini-split',
      pet_policy: 'cats-and-dogs',
      has_gym: true,
      has_dishwasher: true,
      floor: 3,
      broker_fee_months: 0,
      lease_term_months: 12,
    },
    photos: [
      'https://picsum.photos/seed/shunt-kitchen/800/600',
      'https://picsum.photos/seed/shunt-living/800/600',
      'https://picsum.photos/seed/shunt-bed/800/600',
      'https://picsum.photos/seed/shunt-bath/800/600',
      'https://picsum.photos/seed/shunt-gym/800/600',
    ],
    scores: {
      composite_score: 74.8,
      passes_hard_filters: 1,
      fail_reasons: null,
      akhil_drive_min: 7,
      jayshree_transit_min: 15,
      jayshree_walk_min: 3,
      jayshree_transfers: 0,
      jayshree_transit_route: 'Route 39',
      newton_drive_min: 20,
      kitchen_modernity: 8,
      natural_light: 8,
      bathroom_quality: 8,
      overall_condition: 8,
      bedroom_size_score: 7,
      walk_coffee: 4.0,
      walk_park: 5.0,
      walk_grocery: 7.0,
      walk_restaurant: 5.0,
      walk_library: 15.0,
      walk_transit_stop: 2.5,
      nearest_transit_stop: 'S Huntington Ave @ Perkins St',
      nearest_transit_route: 'Route 39',
      ai_summary: 'Well-appointed 2BR on S Huntington with gym, in-unit laundry, and excellent transit access. Moderate price.',
      ai_notes: '{"red_flags":[],"highlights":["gym","in-unit laundry","mini-split AC","excellent transit","no broker fee"]}',
      ai_confidence: 0.91,
    },
  },

  // --- Fail hard filters ---
  {
    listing: {
      id: 'seed-008',
      source: 'craigslist',
      source_url: 'https://boston.craigslist.org/gbs/apa/d/mission-hill-studio/seed008.html',
      source_id: 'seed008',
      title: '1BR/1BA Mission Hill - Near Hospitals',
      price: 2200,
      bedrooms: 1,
      bathrooms: 1,
      sqft: 600,
      address: '50 Wigglesworth St, Boston, MA 02120',
      neighborhood: 'Mission Hill',
      lat: 42.3340,
      lon: -71.0980,
      description: 'Cozy 1 bedroom in Mission Hill. Updated bath. Coin laundry in basement. Window AC. Street parking only. No pets.',
      parking_type: 'street',
      laundry_type: 'in-building',
      ac_type: 'window',
      pet_policy: 'no-pets',
      has_gym: false,
      has_dishwasher: false,
      floor: 2,
      broker_fee_months: 1.0,
      lease_term_months: 12,
    },
    photos: [
      'https://picsum.photos/seed/mh-kitchen/800/600',
      'https://picsum.photos/seed/mh-bed/800/600',
    ],
    scores: {
      composite_score: 0,
      passes_hard_filters: 0,
      fail_reasons: 'bedrooms 1 != 2; bathrooms 1 < 1.5',
    },
  },
  {
    listing: {
      id: 'seed-009',
      source: 'craigslist',
      source_url: 'https://boston.craigslist.org/gbs/apa/d/jp-expensive-2br/seed009.html',
      source_id: 'seed009',
      title: 'Luxury 2BR/2BA Penthouse JP',
      price: 5200,
      bedrooms: 2,
      bathrooms: 2,
      sqft: 1400,
      address: '500 Centre St, Jamaica Plain, MA 02130',
      neighborhood: 'Jamaica Plain',
      lat: 42.3190,
      lon: -71.1100,
      description: 'Stunning penthouse with panoramic views. Top-of-line everything. Private roof deck. 2 garage spots. Full concierge.',
      parking_type: 'garage',
      laundry_type: 'in-unit',
      ac_type: 'central',
      pet_policy: 'cats-and-dogs',
      has_gym: true,
      has_dishwasher: true,
      floor: 8,
      broker_fee_months: 0,
      lease_term_months: 12,
    },
    photos: [
      'https://picsum.photos/seed/pent-kitchen/800/600',
      'https://picsum.photos/seed/pent-living/800/600',
      'https://picsum.photos/seed/pent-view/800/600',
    ],
    scores: {
      composite_score: 0,
      passes_hard_filters: 0,
      fail_reasons: 'price 5200 outside 0-4500',
    },
  },
  {
    listing: {
      id: 'seed-010',
      source: 'craigslist',
      source_url: 'https://boston.craigslist.org/gbs/apa/d/brookline-village-2br/seed010.html',
      source_id: 'seed010',
      title: 'Charming 2BR/1BA Brookline Village',
      price: 3000,
      bedrooms: 2,
      bathrooms: 1,
      sqft: 850,
      address: '20 Station St, Brookline, MA 02445',
      neighborhood: 'Brookline',
      lat: 42.3330,
      lon: -71.1175,
      description: 'Classic Brookline 2 bed with character. Original hardwood, bay windows. Coin laundry downstairs. No AC. Street parking. Steps to Brookline Village Green Line D stop. Cats OK. Half month broker fee.',
      parking_type: 'street',
      laundry_type: 'in-building',
      ac_type: 'none',
      pet_policy: 'cats-only',
      has_gym: false,
      has_dishwasher: false,
      floor: 2,
      broker_fee_months: 0.5,
      lease_term_months: 12,
    },
    photos: [
      'https://picsum.photos/seed/bv-kitchen/800/600',
      'https://picsum.photos/seed/bv-living/800/600',
      'https://picsum.photos/seed/bv-bed/800/600',
    ],
    scores: {
      composite_score: 0,
      passes_hard_filters: 0,
      fail_reasons: 'bathrooms 1 < 1.5',
    },
  },
];

async function seed() {
  console.log('=== Seeding Database ===');

  const db = createClient({
    url: TURSO_URL,
    authToken: TURSO_AUTH_TOKEN,
  });

  // Initialize schema
  const schemaPath = join(__dirname, '..', 'src', 'lib', 'schema.sql');
  const schema = readFileSync(schemaPath, 'utf-8');
  const statements = schema.split(';').map(s => s.trim()).filter(s => s.length > 0);
  for (const stmt of statements) {
    await db.execute(stmt + ';');
  }
  console.log('[seed] Schema initialized');

  const now = nowISO();

  for (const entry of SEED_LISTINGS) {
    const l = entry.listing;

    // Insert listing
    await db.execute({
      sql: `INSERT OR REPLACE INTO listings (
        id, source, source_url, source_id, title, price, bedrooms, bathrooms,
        sqft, address, neighborhood, lat, lon, description, floor,
        available_date, lease_term_months, broker_fee_months, pet_policy,
        parking_type, laundry_type, ac_type, has_gym, has_dishwasher,
        status, first_seen_at, last_seen_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        l.id, l.source, l.source_url, l.source_id,
        l.title, l.price, l.bedrooms, l.bathrooms,
        l.sqft, l.address, l.neighborhood, l.lat, l.lon,
        l.description, l.floor,
        l.available_date || null, l.lease_term_months, l.broker_fee_months,
        l.pet_policy, l.parking_type, l.laundry_type, l.ac_type,
        l.has_gym ? 1 : 0, l.has_dishwasher ? 1 : 0,
        'new', now, now,
      ],
    });

    // Insert photos
    const photos = entry.photos || [];
    for (let i = 0; i < photos.length; i++) {
      await db.execute({
        sql: 'INSERT OR REPLACE INTO photos (listing_id, url, ordinal) VALUES (?, ?, ?)',
        args: [l.id, photos[i], i],
      });
    }

    // Insert scores
    const s = entry.scores;
    await db.execute({
      sql: `INSERT OR REPLACE INTO scores (
        listing_id, composite_score, passes_hard_filters, fail_reasons,
        akhil_drive_min, jayshree_transit_min, jayshree_walk_min,
        jayshree_transfers, jayshree_transit_route, newton_drive_min,
        kitchen_modernity, natural_light, bathroom_quality, overall_condition,
        bedroom_size_score, walk_coffee, walk_park, walk_grocery,
        walk_restaurant, walk_library, walk_transit_stop,
        nearest_transit_stop, nearest_transit_route,
        ai_summary, ai_notes, ai_confidence, scored_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        l.id, s.composite_score, s.passes_hard_filters,
        s.fail_reasons || null,
        s.akhil_drive_min || null, s.jayshree_transit_min || null,
        s.jayshree_walk_min || null, s.jayshree_transfers || null,
        s.jayshree_transit_route || null, s.newton_drive_min || null,
        s.kitchen_modernity || null, s.natural_light || null,
        s.bathroom_quality || null, s.overall_condition || null,
        s.bedroom_size_score || null, s.walk_coffee || null,
        s.walk_park || null, s.walk_grocery || null,
        s.walk_restaurant || null, s.walk_library || null,
        s.walk_transit_stop || null, s.nearest_transit_stop || null,
        s.nearest_transit_route || null,
        s.ai_summary || null, s.ai_notes || null,
        s.ai_confidence || null, now,
      ],
    });

    const status = s.passes_hard_filters ? `score=${s.composite_score}` : `FAILED: ${s.fail_reasons}`;
    console.log(`[seed] ${l.title} -> ${status}`);
  }

  console.log(`\n[seed] Inserted ${SEED_LISTINGS.length} listings`);
  console.log('=== Seeding Complete ===');
}

seed().catch(err => {
  console.error('Seed error:', err);
  process.exit(1);
});
